---
title: "My Own Project"
subtitle: "The Final Assignment"
author: "Shipon Miah"
date: today
date-format: "MMM D, YYYY"

toc: true
toc-depth: 6
echo: true

fig-cap-location: bottom
tbl-cap-location: top
fig-dpi: 700

format:
  html:
    title-block-banner: true
    toc-float: true
    code-fold: true
    code-summary: "Show the code"
    theme: minty
  docx: default
---

# Objectives

As the questions are outlined, the objectives of this assignment is to input data, wrangling it, save the cleaned data in a organized sub-folder, load the data, make summary to represent a table, some graphs (mostly ggplot), focus/visualize on the fruit quality (with the help of spider chart) based on different parameters.

## Loading Libraries and Packages

The packages with libraries are required to be installed in the system/environment of rstuio for this assignment are pacman, tidyverse, here, flextable, fmsb, scales, patchwork, and RColorBrewer.

::: {.callout-note appearance="simple"}
## Spider Graph

Here, I have desgined a new graph, which is called spider graph. I kind of like it to show the fruit's quality contrasting different quality attributing characters parameters. Although, its a huge process to wrangle the data for this graph but I liked it, and it can visualize beautifully. Another point to add about this graph. As I have added 3 spider graph in one row, so it look small but if I can zoom it then it becomes big and clear or if I will dynamically decrease the browser's window size then the column of the spider graph automatically get one another and becomes bigger, which is really beautiful to look!
:::


## Data Input

After completing the normal tidyness of the excel file (available at data/raw.data folder), the comparatively cleaned file is then kept in the folder data/raw.data. Now lets input the data from the excel file to the rstudio.


## Data Wrangling

As the data is now loaded in the environment we need to do a lot of sorting/wrangling to get the objectives. This document contains a lot of data. We need to wrangle the data to fulfill our objectives of the assignment as well as to visualize the data in a meaningful way. Here, I will select/wrangle/sort/clean only a few parameters. So, lets get started.

# Conclusion

I think this is all that I required to submit for this assignment. It seems to me now, wrangling and visualizing are possible in the the preferable ways but thinking/imagination is the first thing to perform before coding.

::: callout-note
I noticed that keeping warning/message option sometimes helpful to understand what is going wrong. I mean, it gives hints to look at the right point of the code chunk. So, I always keep option open. But, sometimes when I go to render the document into html, the warning/message showing up. So, after completing the objectives of this assignment I have put warning/message off for every code chunk, as the objectives are completed so no need to show the warning/message. It will be helpful if I get one code for the whole qmd file to off the warning/message. I searched but did not get anything helpful yet. So, put (message=FALSE, warning=FALSE) in between every r code header.
:::
